Добавление методов взаимодействия с блоками в игровом пространстве
bmstu-iu9/utp2019-2-2d-game pull request #15
Opened 2019-07-03 15:27 UTC by Irautak

2019-07-03 19:50 UTC, Mitbus requested changes

2019-07-03 19:50 UTC, Mitbus commented on Scripts/GameArea.js
> +			return new Block(0, "air", coordinates, 100, 0,
Давайте использовать не блоки воздуха, а просто undefined (ничего). Так в случае необходимости мы сможем вводить прозрачные для игрока блоки + не придется отрисовывать лишние блоки, когда их нет

2019-07-03 19:50 UTC, Mitbus commented on Scripts/GameArea.js
> +	constructor(id, type, coordinates, durability, brightness, isCollissed, isPlatform, isClickable){
Добавьте описание сложных полей блока (не понятно, что такое id и type, например)

2019-07-03 19:50 UTC, Mitbus commented on Scripts/GameArea.js
> +		this.updateRadius = (coordinates) => {
Можно вызывать не каскад функций выше, а одну в цикле с разными параметрами? Копипаст - это плохо

2019-07-03 19:50 UTC, Mitbus commented on Scripts/GameArea.js
> +		// =====Группа функций, возвращающая координаты относительно заданной=====
Можно объединить

2019-07-04 20:26 UTC, Mitbus approved these changes

2019-07-04 20:26 UTC, Shaniser approved these changes

2019-07-04 20:28 UTC, merged