Develop
bmstu-iu9/utp2019-2-2d-game pull request #89
Opened 2019-07-18 10:54 UTC by Shaniser

Может уже в мастер?

2019-07-18 14:44 UTC, Mazdaywik requested changes
Есть нарушение стиля оформления кода. Содержательно смысл кода проверить не могу, поскольку в ваших исходниках не разбираюсь.

2019-07-18 14:44 UTC, Mazdaywik commented on Scripts/gameArea.js
> +            let grad = (y > this.elevationMap[x]) ? 1 : ((y < 0.9 * this.elevationMap[x]) ? 0.2 : ((y - 0.9 * this.elevationMap[x]) / (0.1 * this.elevationMap[x]) * 0.8 + 0.2));
Я насчитал 178 символов, что на 25 % больше лимита в Wiki (120 символов).

Причём оператор `? :` очень хорошо разбивается на строчки:
```JavaScript
            let grad =
                (y > this.elevationMap[x]) ? 1 :
                ((y < 0.7 * this.elevationMap[x]) ? 0.2 :
                ((y - 0.7 * this.elevationMap[x]) / (0.3 * this.elevationMap[x]) * 0.8 + 0.2));
```

2019-07-18 16:32 UTC, Mitbus commented
В блоке поведения воды в `gameArea.js` некоторые условия слишком сложные, еще и оформлены так, что их трудно читать.

2019-07-18 16:39 UTC, whitequartz commented
> В блоке поведения воды в `gameArea.js` некоторые условия слишком сложные, еще и оформлены так, что их трудно читать.

@Irautak

2019-07-18 16:53 UTC, Mitbus commented
Посмотрел все, кроме `gameArea.js`, `player.js`, `worldGeneration.js`, `level.js`. В них не могу проверить смысл кода т.к. знаю новые места в них слишком поверхностно.

2019-07-18 20:35 UTC, Mazdaywik commented
> В блоке поведения воды в `gameArea.js` некоторые условия слишком сложные, еще и оформлены так, что их трудно читать.

Хороший способ борьбы со сложными условиями — вынесение их в отдельную функцию (метод) с понятным именем. Либо используя вспомогательные булевские переменные, но тоже с понятными именами.

Например:
```JavaScript
                if (n > 0
                        && ((startX - x) * (startX - x) + (startY - y) * (startY - y)
                            < (startX - nextX) * (startX - nextX) + (startY - nextY) * (startY - nextY))
                        && nextX >= 0
                        && nextY >= 0
                        && nextX < width
                        && nextY < height
                        && (shadowMap[nextX][nextY] === undefined
                            || (isNatural && shadowMap[nextX][nextY] % 1000 < n)
                            || (!isNatural && Math.floor(shadowMap[nextX][nextY] / 1000) < n))) {
```
Это можно упростить так:
```JavaScript
                const distStart = (x, y) => ((startX - x) * (startX - x) + (startY - y) * (startY - y));
                const inRange = (min, val, max) = ((min <= val) && (val < max));
                if (n > 0
                        && (distStart(x, y) < distStart(nextX, nextY))
                        && inRange(0, nextX, width)
                        && inRange(0, nextY, height)
                        && (shadowMap[nextX][nextY] === undefined
                            || (isNatural && shadowMap[nextX][nextY] % 1000 < n)
                            || (!isNatural && Math.floor(shadowMap[nextX][nextY] / 1000) < n))) {
```
Можно упрощать и дальше:
```JavaScript
                const distStart = (x, y) => ((startX - x) * (startX - x) + (startY - y) * (startY - y));
                const inRange = (min, val, max) = ((min <= val) && (val < max));
                const nextIsFurther = distStart(x, y) < distStart(nextX, nextY);
                const nextInScreen = inRange(0, nextX, width) && inRange(0, nextY, height);
                if (n > 0
                        && nextIsFurther
                        && nextInScreen
                        && (shadowMap[nextX][nextY] === undefined
                            || (isNatural && shadowMap[nextX][nextY] % 1000 < n)
                            || (!isNatural && Math.floor(shadowMap[nextX][nextY] / 1000) < n))) {
```
И ещё дальше:
```JavaScript
                const distStart = (x, y) => ((startX - x) * (startX - x) + (startY - y) * (startY - y));
                const inRange = (min, val, max) = ((min <= val) && (val < max));
                const nextIsFurther = distStart(x, y) < distStart(nextX, nextY);
                const nextInScreen = inRange(0, nextX, width) && inRange(0, nextY, height);
                const acceptableWTFofShadowMap = shadowMap[nextX][nextY] === undefined
                    || (isNatural && shadowMap[nextX][nextY] % 1000 < n)
                    || (!isNatural && Math.floor(shadowMap[nextX][nextY] / 1000) < n)
                if (n > 0 && nextIsFurther && nextInScreen && acceptableWTFofShadowMap) {
```
Смысл последнего условия про `shadowMap` от меня далёк, надеюсь, вы сами сможете упростить код так, чтобы даже я его понял.

Вообще, смысл условия мне не ясен, поэтому я разбирал его наугад. Скорее всего, я где-то ошибся. Я думаю, что автор кода, расписывая условие подобным образом, всё всем (включая меня) станет понятнее.

2019-07-18 20:43 UTC, Mazdaywik submitted a review, later dismissed
Посмотрите внимательно Files changed. Зачем нужно делать исполнимые картинки? Исполнимые! Картинки! Зачем 755 для `player.png`?

Чтобы атрибуты сделать корректными (и логичными), нужно выполнить следующие команды. На Windows;
```Batch
git update-index --chmod=-x Images/*.png LICENCE README.md (и другие файлы)
git commit -m "Исправлены атрибуты у некоторых файлов
```
На unix-like:
```Bash
chmod -x Images/*.png LICENCE README.md (и другие файлы)
git add -p
(на запросы изменения флагов отвечаем y, на остальные n)
git commit -m "Исправлены атрибуты у некоторых файлов"
```

(Да, кавычку на Windows можно не закрывать)

2019-07-18 20:51 UTC, Mazdaywik commented
Вы, кстати, распишите словами, что означает это длинное условие, и я предложу более точный вариант его декомпозиции.

2019-07-18 20:53 UTC, Mazdaywik commented on Scripts/gameArea.js
> +                let endY = Math.floor(player.y + Player.HEIGHT);
Хороший стиль, который пропагандировал @alex-qrcs, писать `const` вместо `let` везде, где только можно. Здесь, например, лучше написать 4 `const`’а.

2019-07-18 23:37 UTC, Mitbus commented on Scripts/gameArea.js
> +                            ||  this.map[x + 1][y][layout] < 9000)
Мне кажется, что помимо вынесения однотипных условий в функцию стоит еще пояснить, что за константы используются и почему именно они

2019-07-19 00:52 UTC, Mitbus commented on Scripts/gameArea.js
> +                        let direction = Math.floor((+block.id - 9000) / 8);
Почему мы храним id блока строкой, но при каждом обращении переводим его к числу?

2019-07-19 00:52 UTC, Mitbus commented on Scripts/level.js
> +    					currentBlock.durability -= deltaTime * effK;
Точно не знаю, в чем разница, но слышал рекомендацию использовать `===` вместо `==`. И еще тут нарушена стилизация кода

2019-07-19 13:58 UTC, Mitbus commented
@Irautak, почему ты в `gameArea.js` используешь стрелочные функции? Насколько я понимаю, тут удобнее использовать `function`. Если ты пишешь `this.a = () => {...};` , то ты фактически для каждого объекта класса объявляешь поле и кладешь туда функцию, к тому же из этой функции недоступен `this`. В данном случае мы создаем не более одного объекта класса, поэтому нет почти никаких проблем, но в общем случае нужно быть внимательным.

2019-07-19 14:02 UTC, whitequartz commented
> @Irautak, почему ты в `gameArea.js` используешь стрелочные функции? Насколько я понимаю, в этом случае лучше использовать `function`. Если ты пишешь `this.a = () => {...};` , то ты фактически для каждого объекта класса объявляешь поле и кладешь туда функцию, к тому же из этой функции недоступен `this`. В данном случае мы создаем не более одного объекта класса, поэтому нет почти никаких проблем, но в общем случае нужно быть внимательным.

Нам ведь на лекциях советовали не использовать устаревший function, а только анонимные функции. Разве нельзя из анонимной функции получить this?

2019-07-19 17:53 UTC, Mazdaywik commented
@whitequartz, а что, консольными командами исправить атрибуты не получилось? Потому что удалять и снова добавлять файл вообще говоря не очень хорошо. Гит в этом случае уже не сможет отследить историю строчек файла для команды `git blame`. Для бинарных файлов это не актуально, а вот для `README.md` Вы историю потеряли.

2019-07-19 18:01 UTC, Mitbus commented
> @whitequartz, а что, консольными командами исправить атрибуты не получилось? Потому что удалять и снова добавлять файл вообще говоря не очень хорошо. Гит в этом случае уже не сможет отследить историю строчек файла для команды `git blame`. Для бинарных файлов это не актуально, а вот для `README.md` Вы историю потеряли.

Иногда замечаю в коммитах такие изменения файлов: все содержимое удалено, а потом добавлено тоже самое. Это считается изменением истории или мы тоже ее так теряем? И еще, мы пытались переименовать файл, но гит не хотел видеть эти изменения и мы его пересоздали.

2019-07-19 18:03 UTC, whitequartz commented
> @whitequartz, а что, консольными командами исправить атрибуты не получилось? Потому что удалять и снова добавлять файл вообще говоря не очень хорошо. Гит в этом случае уже не сможет отследить историю строчек файла для команды `git blame`. Для бинарных файлов это не актуально, а вот для `README.md` Вы историю потеряли.

Через сайт вся история отображается
![alt text](https://i.imgur.com/1xQIIEd.jpg)

2019-07-19 18:07 UTC, Mitbus commented
`game.js` -> `preprocessing.js`

2019-07-19 18:18 UTC, Mitbus commented
Например, в этом mr `level.js` отмечен как полностью удаленный, а потом добавлен (хотя на самом деле добавлены новые методы)

2019-07-19 19:17 UTC, Mazdaywik commented
@whitequartz, через командную строку нет. Вот вывод `git blame README.md`:
```
cda7a636 (whitequartz 2019-07-19 16:56:35 +0300  1) # utp2019-2-2d-game
cda7a636 (whitequartz 2019-07-19 16:56:35 +0300  2) 2D-игра, упрощённый вариант Terraria, команда Алексея Костюченко
cda7a636 (whitequartz 2019-07-19 16:56:35 +0300  3) 
cda7a636 (whitequartz 2019-07-19 16:56:35 +0300  4) Участники:
cda7a636 (whitequartz 2019-07-19 16:56:35 +0300  5) * Алексей Костюченко
cda7a636 (whitequartz 2019-07-19 16:56:35 +0300  6) * Илья Каркин
cda7a636 (whitequartz 2019-07-19 16:56:35 +0300  7) * Илья Щербаков
cda7a636 (whitequartz 2019-07-19 16:56:35 +0300  8) * Искандер Омуров
cda7a636 (whitequartz 2019-07-19 16:56:35 +0300  9) * Никита Волков
cda7a636 (whitequartz 2019-07-19 16:56:35 +0300 10) * Светлана Пирожкова
cda7a636 (whitequartz 2019-07-19 16:56:35 +0300 11) * Надим Абдул Гани
cda7a636 (whitequartz 2019-07-19 16:56:35 +0300 12) * Владислав Ломтев
```

2019-07-19 19:33 UTC, Mazdaywik commented
@Mitbus, ГитХаб здесь показывает разницу между ветками `master` и `develop`. В рамках текущей ветки действительно были добавлены только методы. Но в ветку `master` @Shaniser закоммитил файл `level.js` с концами строк Windows (`\r\n`): 66215a6397896aa3f5f8667f84606b09adfb9ab9.

Исправил в<span>&nbsp;</span>#92. Хотя мог бы, пользуясь правом администратора, напрямую закоммитить в `master`.

2019-07-19 19:41 UTC, Mazdaywik commented
Чтобы вы не мучались с удалением файлов из web-интерфейса, я исправил атрибуты сам: #93.

2019-07-20 08:54 UTC, Mazdaywik reviewed
Стало существенно понятнее! Хороший, годный рефакторинг!

2019-07-20 08:54 UTC, Mazdaywik commented on Scripts/gameArea.js
> +                            || (!isNatural && this.getArtificalLight(nextX, nextY) < n))) {
Во! Теперь всё понятнее. Даже без комментариев.

Можно пойти и дальше:
```JavaScript
const getLight = isNatural ? (x, y) => this.getNaturalLigth(x, y) : (x, y) => this.getArtificalLight(x, y);
if (… || (getLight(x, y) < n) {
```
Проверка `(isNatural && this.getNaturalLight(x, y) < n) || (!isNatural && this.getArtificalLight(x, y) < n))` в коде много раз повторяется, поэтому имеет смысл вынести в отдельную функцию.

2019-07-20 09:00 UTC, Mazdaywik commented on Scripts/gameArea.js
> +                            || (!isNatural && this.getArtificalLight(nextX, nextY) < n))) {
Добавлю. Свет он не «натуральный», а «естественный».

И ещё, комментарии не нужны. Вернее, не нужны те комментарии, которые повторяют код. Например:
```JavaScript
x += 5;  // прибавили пять

//............................................ Искуственный свет меньше n
|| (!isNatural && this.getArtificalLight(nextX, nextY) < n))) {
```

2019-07-20 09:02 UTC, Shaniser commented on Scripts/gameArea.js
> +                            || (!isNatural && this.getArtificalLight(nextX, nextY) < n))) {
<img width="1318" alt="Снимок экрана 2019-07-20 в 12 01 33" src="https://user-images.githubusercontent.com/48556605/61576732-27e48b00-aae6-11e9-9c07-dfb9b5f2648f.png">
Или вопрос к какому-то комменту?

2019-07-20 09:09 UTC, Shaniser commented on Scripts/gameArea.js
> +                            || (!isNatural && this.getArtificalLight(nextX, nextY) < n))) {
> Проверка `(isNatural && this.getNaturalLight(x, y) < n) || (!isNatural && this.getArtificalLight(x, y) < n))` в коде много раз повторяется, поэтому имеет смысл вынести в отдельную функцию.

1) isNatural локальная переменная конкретных функций
2) this.getLight уже имеется, и означает итоговую освещённость блока (введение подобной функции может привести к путанице)

2019-07-20 10:11 UTC, Mazdaywik commented on Scripts/gameArea.js
> +                            || (!isNatural && this.getArtificalLight(nextX, nextY) < n))) {
Я имел ввиду добавить
```JavaScript
const ligthBelowThreshold = (x, y) => (isNatural && this.getNaturalLigth(x, y) < n)
    || (!isNatural && this.getArtificalLight(x, y) < n);
```
в начале метода `addLightRound`, поскольку этот код громоздкий и повторяется дважды. А вместо `(x && y) || (!x && z)` можно записать `x ? y : z`.

2019-07-20 15:48 UTC, Mazdaywik commented on Scripts/player.js
> +                    * Math.acos((x - this.x) / hypotenuse(x - this.x, y - this.y - Player.HEIGHT / 2));
Навскидку: почему тут не используется более логичная функция [`Math.atan2`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Math/atan2)?

2019-07-20 15:50 UTC, Shaniser commented on Scripts/player.js
> +                    * Math.acos((x - this.x) / hypotenuse(x - this.x, y - this.y - Player.HEIGHT / 2));
Деление на 0

2019-07-20 18:16 UTC, Mazdaywik commented on Scripts/player.js
> +                    * Math.acos((x - this.x) / hypotenuse(x - this.x, y - this.y - Player.HEIGHT / 2));
Функция `atan2` не делит на ноль. Её результат не определён для вызова `atan2(0, 0)`, но для остальных комбинаций результат осмыслен:
```JavaScript
atan2(100500, 0) = 0
atan2(0, 42) = π/2
atan2(-666, 0) = π
atan2(0, -13) = -π/2
```

Посмотрел в справку. Оказывается, у неё определён результат и для `atan2(0, 0)`.

2019-07-20 19:29 UTC, Shaniser commented on Scripts/player.js
> +                    * Math.acos((x - this.x) / hypotenuse(x - this.x, y - this.y - Player.HEIGHT / 2));
Оно того не стоит, в общем (на вскидку работать не начало, а у меня на реализацию всего этого часов 5 ушло)

2019-07-20 22:03 UTC, whitequartz commented
Добавлена 3 версия графического движка

2019-07-20 22:56 UTC, Mazdaywik commented
Опять исполнимые CSS-ки.

2019-07-20 23:02 UTC, Mazdaywik commented on Scripts/preprocessing.js
> +
Пробельчик.

2019-07-20 23:03 UTC, Mazdaywik commented on Scripts/worldGeneration.js
> +                    shadowRound(x, y, x, y, items[worldMap[x][y][GameArea.MAIN_LAYOUT]].brightness, items[worldMap[x][y][GameArea.MAIN_LAYOUT]].isNaturalLight === true);
Тут точно меньше 120 колонок?

2019-07-21 00:40 UTC, Mazdaywik commented on Scripts/gameArea.js
> +											&& this.map[x - 1][y][layout] === undefined) {
В предыдущей строчке стало 135 символов. По-моему, у вас сбилась настройка отступов в текстовом редакторе.

2019-07-21 00:50 UTC, Mazdaywik commented on Scripts/gameArea.js
> +											this.placeBlock(x - 1, y,
Да, похоже, что теперь один отступ равен 8 пробелам.

2019-07-21 00:52 UTC, Mazdaywik commented on Scripts/gameArea.js
> +											this.placeBlock(x - 1, y,
Сами разбирайтесь, коммитить исходники с отступами табуляцией (знак `\t`) или N пробелов. Я не буду участвовать в этом холиваре.

2019-07-21 13:58 UTC, Mazdaywik commented on Scripts/saveWorld.js
> +
Пробельчик. Чтобы их случайно не коммитить, пользуйтесь `git add -p`.

2019-07-21 14:44 UTC, Mitbus commented on Scripts/gameArea.js
> +											this.placeBlock(x - 1, y,
В правилах оформления кода написано: "... с помощью табуляции", хотя почти все используют 4 пробела)
@whitequartz , возможно, стоит заменить это правило на "в одном файле в общем стиле", т.к. правила появились значительно позднее и у всех уже было по-своему

2019-07-21 15:59 UTC, whitequartz commented on Scripts/gameArea.js
> +											this.placeBlock(x - 1, y,
@Mitbus, отредактировал данный пункт

2019-07-21 16:18 UTC, Mazdaywik commented on Scripts/gameArea.js
> +											this.placeBlock(x - 1, y,
Проблема в том, что GitHub отображает табуляции как 8 пробелов, из-за чего через сайт отступы отображаются вдвое больше. Но, я думаю, это можно потерпеть.

Важно, чтобы редакторы у всех были настроены так, чтобы не меняли автоматически `\t` на N пробелов или наоборот. Либо, если меняли, то только в тех строках, которые пользователь явно менял.

2019-07-25 20:19 UTC, Mitbus approved these changes
Думаю, что уже можно добавлять. То, что можно было исправили, а в сложных моментах знаем как можно решать такие проблемы

2019-07-25 20:22 UTC, Mitbus commented
@Mazdaywik , если больше замечаний, то принимайте

2019-07-25 20:44 UTC, whitequartz approved these changes

2019-07-29 22:59 UTC, merged